services:
  - type: web
    name: water-leakage-detection-api
    env: python
    region: singapore  # Optional: choose closest region
    plan: free  # or starter, standard, etc.
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120 --worker-class sync app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_NO_CACHE_DIR
        value: "1"